name: 'Build'
run-name: 'Build'

on:
  push:
    branches: 
      - main

jobs:
  build:
    name: 'Build'
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0        
      
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.1.1
        with:
          nuget-version: latest
      
      - name: Debugging
        run: echo "GITHUB_PATH = ${GITHUB_PATH}"
             echo "GITHUB_ACTION_PATH = ${GITHUB_ACTION_PATH}"
             echo "GITHUB_EVENT_PATH = ${GITHUB_EVENT_PATH}"
      
      - name: Restore Package
        run: nuget restore **/*.sln
        
